POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  "login": "krgaa",
  "password": "8smile8"
}

###

POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "login": "akruglov",
  "password": "8smile8"
}

###

POST http://localhost:8080/api/user/token
Content-Type: application/json

{
  "refreshToken": "e65399a454ddd345781f2747cabcbea619dfe4e14f35aaf54eedf8f7a516b39791797ace6b4e6007a26c23cf5d0c"
}

###

POST http://localhost:8080/api/user/orders
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzcyI6Imh0dHBzOi8vYWtydWdsb3YucnUiLCJhdWQiOlsia3J1Z2xvdiJdLCJleHAiOjE3MTkzMTkwMTR9.VUeCpcf90gSGGZ1uGySSHhDhxhYQiqPlJaJtafPhlkYMeTcI20xhH4FwMZLDVWTBOZ1aESm4RNMOhAH4CIGu6LR0k9RfYtVRvvSEKAdsUfo5qedUAxPeFx8Y70Mz5-kH5XtioKCgyLnyDO2JOUu-PKwAssWzpiR7TWjW32b4rdg

208787473